version: "3.1"
services:
    www:
        build:
            context: /root/www/docker/Apache/
        ports:
            - "80:80"
        volumes:
            - /root/www:/var/www/html/

    db:
      image: postgres:9.6-alpine
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=linux
        - POSTGRES_DB=acu_db
      ports:
        - 5432:5432

    phppgadmin:
        image: dockage/phppgadmin:latest
        ports:
            - 8000:80
        environment:
            - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
            - PHP_PG_ADMIN_SERVER_PORT=5432
            - PHP_PG_ADMIN_SERVER_HOST=db
